version: '3.3'
services:
  frontend:
    image: 6uamy/taecho-fe:latest
    ports:
      - "5173:5173"
  backend:
    image: 6uamy/taecho-be:latest
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    stdin_open: true
    tty: true
