version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    stdin_open: true
    tty: true
