name: Deploy to ECR (frontend)

on:
  push:
    branches: [ "deploy/dockerfile" ]

env:
  AWS_REGION: ap-northeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: 7days-fe # set this to your Amazon ECR repository name
  CONTAINER_NAME: 7days-fe           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate env
      run: |
        echo "VITE_BASE_URL=$VITE_BASE_URL" >> ./client/.env.development
        echo "VITE_BASE_URL=$VITE_BASE_URL" >> ./client/.env.production
        echo "VITE_GOOGLE_MAP_API_KEY=$VITE_GOOGLE_MAP_API_KEY" >> ./client/.env.development
        echo "VITE_GOOGLE_MAP_API_KEY=$VITE_GOOGLE_MAP_API_KEY" >> ./client/.env.production
      env:
        VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        VITE_GOOGLE_MAP_API_KEY: ${{ secrets.VITE_GOOGLE_MAP_API_KEY }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: ecr image build
      working-directory: ./client
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

    - name: ecr image delete
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr batch-delete-image \
          --repository-name 7days-fe \
          --image-ids imageTag=tag1 imageTag=latest

    - name: ecr image push
      working-directory: ./server
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT